navbar:
  blog_title: Mlou
  ground_glass:
    enable: true
index:
  banner_img: https://resty.s3.eu-gb.cloud-object-storage.appdomain.cloud/1634204767855163420476772.jpg
  banner_img_height: 100
  slogan:
    text: 年年岁岁花相似，岁岁年年人不同
post:
  banner_img: https://i.loli.net/2019/11/10/bEJsXxewpOGuRD8.png
  banner_img_height: 70
  default_index_img: https://i.loli.net/2019/11/10/lP3rLNUBaGtSVzc.png
archive:
  banner_img: https://i.loli.net/2019/11/10/egVhFWopA5mP2Hk.png
  banner_img_height: 80
  subtitle: null
category:
  banner_img: https://i.loli.net/2019/11/10/T7Mu8Aod3egmC4Q.png
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: https://i.loli.net/2019/11/10/T7Mu8Aod3egmC4Q.png
  banner_img_height: 80
  subtitle: null
about:
  banner_img: https://i.loli.net/2019/11/10/gcnavZbmepS8d4u.png
  banner_img_height: 80
  subtitle: null
  avatar: https://www.toopic.cn/public/uploads/small/1634204546619163420454662.jpg
  name: Fluid
  intro: An elegant theme for Hexo
links:
  banner_img: https://i.loli.net/2019/11/10/xthHmnbdNerWOqP.png
  banner_img_height: 80
  subtitle: null
  items:
    - title: Fluid Repo
      intro: 主题 GitHub 仓库
      link: https://github.com/fluid-dev/hexo-theme-fluid
      avatar: /img/favicon.png
